name: docker_build

on:
  push:
    branches:
      - master
    paths:
      - plumed/**

jobs:
  docker:
    strategy:
      matrix:
        version: ['cuda-11.3', 'cuda-11.7']
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: plumed/${{ matrix.version }}/Dockerfile
          push: true
          tags: cloudac7/plumed:2.9.0_torch_deepmd_${{ matrix.version }}
